// get all post
GET http://localhost:6969/api/posts
###

// get specific post
GET http://localhost:6969/api/posts/607ed7954089c86ca462b74b
###


// create new post
POST http://localhost:6969/api/posts/
Content-Type: application/json

{
 "author": "Stefan",
  "content": "Minister",
  "likes": 2,
  "date": "Today"
}
###


###

// delete specific post
DELETE http://localhost:6969/api/posts/607ed368a931083360fe1ed0

###

PUT http://localhost:6969/api/posts/607f0c3deb74ad36100f60dc
Content-Type: application/json

{
  "content": "Pooopiii"
}