// get all post
GET http://localhost:6969/api/posts
###

// get specific post
GET http://localhost:6969/api/posts/607ed7954089c86ca462b74b
###


// create new post
POST http://localhost:6969/api/posts/
Content-Type: application/json

{
 "author": "Stefan",
  "content": "Minister",
  "likes": 2,
  "date": "Today"
}
###


###

// delete specific post
DELETE http://localhost:6969/api/posts/607ed368a931083360fe1ed0

###

// update content of specific post from id
PUT http://localhost:6969/api/posts/607f0c3deb74ad36100f60dc
Content-Type: application/json

{
  "content": "Pooopiii"
}


###
// PROFILES

GET http://localhost:6969/api/profiles

###

POST http://localhost:6969/api/profiles
Content-Type: application/json

{
  "userName": "xxxdankNwetxxx",
  "password": "1234",
  "role": "Pro-boy",
  "name": "Knut Knutsson"
}

### 
// get specific character, from ID 
GET http://localhost:6969/api/profiles/607f17cd2fbe664884221b6e

### 
// delete specific character, from ID 
DELETE http://localhost:6969/api/profiles/607f12092fbe664884221b6d


###


PUT http://localhost:6969/api/profiles/607f17cd2fbe664884221b6e
Content-Type: application/json

{
  "password": "2345",
  "name": "Olof Swagsson"
}


